### ISSUE TITLE
User Story: Very active person

### ISSUE THREAD

**Issue by MFLind** [MFLind/My_First_agile_project#1]
### Very active person:
They can use this website to find other people to run with. At the same time they are training they also find new friends. They can go with the running grupp and drink coffee. 

#### Acceptance Criteria:
- It need to be other people there.
- They need to go and run. 
- They need to go and drink coffee.

#### Tasks
- [ ] Making basic website (5 story points).
- [ ] Make a schedule for run (2 story points).
- [ ] Make an agreement with coffeehouse (2 story points).

Total story points: 9.
