### ISSUE TITLE
User story: Not so active person

### ISSUE THREAD

**Issue by MFLind** [MFLind/My_First_agile_project#2]
### Not so active person:
They can select a pass thet fits them. They does not need to run every pass on the schedule. They find new friends and have fun. They can go with the running grupp and drink coffee.

#### Acceptance Criteria:
- It need to be a schedule so they can select a pass.
- It need to be other people there.
- They need to go and drink coffee. 

#### Tasks
- [ ] Marking basic website (5 story points).
- [ ] Make a schedule for run (2 story points).
- [ ] Make an agreement with coffeehouse (2 story points).

Total story points: 9.
