### ISSUE TITLE
User story: System administrator

### ISSUE THREAD

**Issue by MFLind** [MFLind/My_First_agile_project#3]
### System administrator:
The system administrator need to have access to the code so they can make changes in the code. The system administrator should have easy monitor view to see system status.

#### Acceptance Criteria:
- Have a good communication with the users.
- Cloud provider should have monitor tool.
- They should have a good internet connection. 

#### Tasks
- [ ] Evaluate and select cloud provider (2 story points).
- [ ] Make a form so people can write things thet maybe need to change (1 story points).
- [ ] Make sure they have a good internet connection (1 story points).

Total story points: 4.

**Comment by MFLind** [comment]
### System administrator:

#### Acceptance Criteria:
- 
- 
-  

#### Tasks
- [ ]
- [ ] 
- [ ]
