### ISSUE TITLE
User story: Leader

### ISSUE THREAD

**Issue by MFLind** [MFLind/My_First_agile_project#4]
### Leader:
The leader can use the website to se how meny people thet have signed up on every pass. They can also se were they are going to run that pass. They can also se how meny people they are going to be drinking coffee with. 

#### Acceptance Criteria:
- It need to be a place were the leader can se how meny people thet have signed up.
- It need to be a place there they can se were they are going to run.
-  It need to be a place were they can se how meny they are going to be to drink coffee.

#### Tasks
- [ ] Make a form there the runner can signed up on (1 story points).
- [ ] Make a map there they can see were the are going to run (3 story points). 
- [ ] Make an agreement with coffeehouse (2 story points).

Total story points: 6.
