### ISSUE TITLE
User story: Medium active

### ISSUE THREAD

**Issue by MFLind** [MFLind/My_First_agile_project#5]
### Medium active:
They can find other people to run whit. They can also select a pass thet match their schedule. They can also find new friends. They can also go and drink coffee with they running grupp. 

#### Acceptance Criteria:
- It need to be a schedule so they can select a pass.
- It need to be other people there.
- They need to go and drink coffee. 

#### Tasks
- [ ] Marking basic website (5 story points).
- [ ] Make a schedule for run (2 story points).
- [ ] Make an agreement with coffeehouse (2 story points). 

Total story points: 9.
